name: my_custom_staggered_grid_view
description: Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
version: 1.0.0+3
homepage: https://github.com/kverkholomova13/custom_flutter_staggered_grid_view.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
